"""add_completed_and_paid_flags_to_task

Revision ID: 8bec255a313a
Revises: 0b3e78998293
Create Date: 2026-03-28 09:44:59.702992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bec255a313a'
down_revision: Union[str, None] = '0b3e78998293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_paid')
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
