"""add color to task status

Revision ID: 0b3e78998293
Revises: initial
Create Date: 2026-03-24 07:27:14.024261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b3e78998293'
down_revision: Union[str, None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'settings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('app_settings_user_id_key'), 'app_settings', type_='unique')
    op.drop_index(op.f('ix_app_settings_user_id'), table_name='app_settings')
    op.create_index(op.f('ix_app_settings_user_id'), 'app_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_pomodoro_intervals_id'), 'pomodoro_intervals', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.alter_column('recurring_tasks', 'frequency_data_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('recurring_tasks_task_id_key'), 'recurring_tasks', type_='unique')
    op.drop_index(op.f('ix_recurring_tasks_task_id'), table_name='recurring_tasks')
    op.create_index(op.f('ix_recurring_tasks_task_id'), 'recurring_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_recurring_tasks_id'), 'recurring_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_task_lists_id'), 'task_lists', ['id'], unique=False)
    op.add_column('task_statuses', sa.Column('color', sa.String(length=7), nullable=False, server_default='#808080'))
    op.create_index(op.f('ix_task_statuses_id'), 'task_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_time_segments_id'), 'time_segments', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_time_segments_id'), table_name='time_segments')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_task_statuses_id'), table_name='task_statuses')
    op.drop_column('task_statuses', 'color')
    op.drop_index(op.f('ix_task_lists_id'), table_name='task_lists')
    op.drop_index(op.f('ix_recurring_tasks_id'), table_name='recurring_tasks')
    op.drop_index(op.f('ix_recurring_tasks_task_id'), table_name='recurring_tasks')
    op.create_index(op.f('ix_recurring_tasks_task_id'), 'recurring_tasks', ['task_id'], unique=False)
    op.create_unique_constraint(op.f('recurring_tasks_task_id_key'), 'recurring_tasks', ['task_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('recurring_tasks', 'frequency_data_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_pomodoro_intervals_id'), table_name='pomodoro_intervals')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_user_id'), table_name='app_settings')
    op.create_index(op.f('ix_app_settings_user_id'), 'app_settings', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('app_settings_user_id_key'), 'app_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('app_settings', 'settings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
